apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mongo-app
  namespace: argocd
spec:
  project: default
  destination:
    namespace: default
    server: "https://kubernetes.default.svc"
  source:
    path: manifest 
    repoURL: "https://github.com/Swapnil20001/mongo-argo.git"
    targetRevision: HEAD

  syncPolicy:
    automated:
      selfHeal: true
      prune: true

